### ISSUE TITLE
Is the design finished?

### ISSUE THREAD

**Issue by Arakistech** [JGAguado/Smart_Plant#2]
In the Eagle layout I see like it is not finished. Can you please share latest PCB files?

Thanks

**Comment by JGAguado** [comment]
Hi @Arakistech, sorry it was a little bit messy... I made now a release (https://github.com/JGAguado/Smart_Plant/releases/tag/V1R1) that contains the files as in the Hackaday post. Soon I will be publishing the V1R2 with the patch board features implemented all in one PCB.
