### ISSUE TITLE
Saturation of brightness sensor

### ISSUE THREAD

**Issue by TheRocken** [JGAguado/Smart_Plant#3]
The brightness sensor seems to go into a kind of saturation already at low brightness. Is this a known and normal behaviour? The usefulness of the sensor is thus rather low for me. The maximum value seems to be at 626.8 Lux.
![birghtness sensor](https://user-images.githubusercontent.com/17852728/236916961-f251d963-442f-4338-b34f-db9b42aea062.png)

**Comment by JGAguado** [comment]
Which version do you have, V1R1 or V1R2? 
In the V1R1 the sensor is a SMD photodiode (https://datasheet.lcsc.com/lcsc/1806131537_Everlight-Elec-ALS-PT19-315C-L177-TR8_C146233.pdf)  and cannot be easily replaced.
However on the V1R2, the standard sensor I included is a 10k photoresistor (https://z3d9b7u8.stackpathcdn.com/pdf-down/G/L/5/GL5549_SENBA.pdf) that can be replaced with another LDR or a photodiode more suited to your light conditions.

**Comment by JGAguado** [comment]
Let me know once you do it, the behaviour, I am also making continuous test to improve it and your feedback is really appreciated! I will close the issue for the moment, but feel free to reopen it if you need it.
